aiortc_ros_msgs/SDP offer

# payload could be token to identify client or others
# such as token + requested camera stream to connect to
# TODO: implement JWT or Oauth
string payload
---
aiortc_ros_msgs/SDP answer
# unique id assigned by server to identify connection
string conn_uuid